export const EN_Content = {
  TAB_NAME: "Home",
  START_MSG: "Start by adding a book using the +Add Book button",
  SEARCH_BAR_PLACEHOLDER: "Search by title",
  SORT_TITLE: "Sort by Title",
  SORT_DATE: "Sort by Date",
  ADD_BOOK: "+Add Book",
  SAVE: "Save",
  EDIT: "Edit",
  DELETE: "Delete",
  NEW_BOOK: "Add Book",
  EDIT_BOOK: "Edit Book",
  COMMENTS: "Comments",
  COMMENT_SWITCH_USER: "Tap to switch user",
  COMMENT_PLACEHOLDER: "Add a comment",
  POST: "Post",
  PAGE: "page",
  BOOK_TITLE_PLACEHOLDER: "Book Title",
  BOOK_DESC_PLACEHOLDER: "Brief description of the book",
  LIBRARY_TITLE: "Discover new adventures!",
  SEARCH_BOOKS_PLACEHOLDER: "Search for books",
  LANGUAGE: "LANGUAGE",
  THEME: "THEME",
  DARK_MODE: "Dark Mode",
  LIBRARY: "Library",
  SETTINGS: "Settings",
};
