export const ES_HomeScreen = {
  TAB_NAME: "Inicio",
  START_MSG: "Empieza agregando un Libro usando el boton +Nuevo Libro",
  SEARCH_BAR_PLACEHOLDER: "Buscar por Titulo",
  SORT_TITLE: "Por Titulo",
  SORT_DATE: "Por Fecha",
  ADD_BOOK: "+Nuevo Libro",
  SAVE: "Guardar",
  EDIT: "Editar",
  COMMENTS: "Comentarios",
  COMMENT_SWITCH_USER: "Cambiar usuario",
  COMMENT_PLACEHOLDER: "Agrega un comentario",
  PAGE: "pagina",
  BOOK_TITLE_PLACEHOLDER: "Titulo del Libro",
  BOOK_DESC_PLACEHOLDER: "Breve descripcion del libro",
  LIBRARY_TITLE: "Descubre nuevas aventuras!",
  SEARCH_BOOKS_PLACEHOLDER: "Buscar libros",
  LANGUAGE: "IDIOMA",
  THEME: "APARIENCIA",
  DARK_MODE: "Modo Oscuro",
};
